{
 "title": "Products observability — RED",
 "tags": [
  "lab2",
  "products",
  "RED"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Интенсивность запросов (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(products_demo_http_requests_total{path!=\"/\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Доля ошибок 5xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(products_demo_http_errors_total[5m])) / clamp_min(sum(rate(products_demo_http_requests_total{path!=\"/\"}[5m])), 0.000001)",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Время ответа p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(products_demo_http_request_duration_seconds_bucket{path!=\"/\"}[5m])))",
     "legendFormat": "p95 {{path}}"
    }
   ]
  }
 ]
}